version: '3'

services:
    node:
        image: node:alpine
        working_dir: /app
        command: /app/entrypoint.sh
        user: '1000'
        volumes:
            - ./:/app
        ports:
            - 80:8080
        environment:
            PORT: 8080
            DB_DRIVER: sql
            DB_URI: mysql://chat:chat@mysql:3306/chat
    mysql:
        image: mysql:5.7.39
        container_name: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE:-chat}
            MYSQL_USER: ${DB_USER:-chat}
            MYSQL_PASSWORD: ${DB_PASSWORD:-chat}
        volumes:
            - chat_mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.0
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        depends_on:
            - mysql

    mongo:
        image: mongo:4.4-focal
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - chat_mongo:/data/db

    mongo_express:
        image: mongo-express:1.0.0-alpha.4
        container_name: mongo_express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017
        depends_on:
            - mongo

volumes:
    chat_mysql:
        external: false
    chat_mongo:
        external: false
