### Get All Users
GET /api/v1/users
Host: localhost:8888

### Register New User
POST /api/v1/users
Host: localhost:8888
Content-Type: application/json

{
    "name": "jhoan",
    "email":"jhoan@gmail.com",
    "password":"12345"
}

### Unregister User
DELETE /api/v1/user
Host: localhost:8888
Content-Type: application/json

{
    "email":"jhoan@gmail.com"
}

### Login New User
POST /api/v1/auth/login
Host: localhost:8888
Content-Type: application/json

{
    "email":"jhoan@gmail.com",
    "password":"12345"
}

### Validate token
POST /api/v1/auth/validate
Host: localhost:8888
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Impob2FuIiwiZW1haWwiOiJqaG9hbkBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIyLTEwLTEzVDAzOjIwOjEyLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTEwLTEzVDAzOjIwOjEyLjAwMFoiLCJpYXQiOjE2NjU2Mzk3NTgsImV4cCI6MTY2NTY0MzM1OH0.hgxK_X47iWFGwUydkAntj_g_RKWvFrelDJQxYiq55j0
Content-Type: application/json

### Chat for the user
GET /api/v1/chats
Host: localhost:8888
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Impob2FuIiwiZW1haWwiOiJqaG9hbkBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIyLTEwLTEzVDAzOjIwOjEyLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTEwLTEzVDAzOjIwOjEyLjAwMFoiLCJpYXQiOjE2NjU2Mzk3NTgsImV4cCI6MTY2NTY0MzM1OH0.hgxK_X47iWFGwUydkAntj_g_RKWvFrelDJQxYiq55j0
Content-Type: application/json